version: 2

release:
  github:
    owner: catalystgo
    name: protosync
  name_template: "{{ .Tag }}"
  make_latest: true

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    id: "protosync"
    binary: protosync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
