version: '3'

vars:
  GOBIN: "$(pwd)/bin"
  DOCKER_IMAGE: "catalystgo/protosync"

tasks:
  build:
    cmds:
      - go build -o bin/protosync -ldflags="-X github/catalystgo/protosync/internal/build.Version={{.VERSION}}" main.go
    vars:
      VERSION: "$(git describe --tags --always --dirty)"

  release:
    cmds:
      - goreleaser release --snapshot --clean

  mock:
    cmds:
      - "{{.GOBIN}}/mockgen -source=internal/downloader/client.go -destination=internal/downloader/mock/client.go -package=mock"
      - "{{.GOBIN}}/mockgen -source=internal/service/client.go -destination=internal/service/mock/client.go -package=mock"

  format:
    cmds:
      - task: go_files
        vars: { COMMAND: 'gofmt -w  {} +'}
      - task: go_files
        vars: { COMMAND: '{{.GOBIN}}/goimports -w  {} +'}

  test:
    desc: "Run all tests and generate coverage report (excludes some packages)"
    cmds:
      - go test -cover -json -coverprofile=coverage.out 
        $(go list ./... | grep -Ewv "(mock$|cmd$)") | {{.GOBIN}}/gotestfmt

  lint:
    desc: "Run revive linter"
    cmds:
      - "{{.GOBIN}}/revive
        -config revive.toml
        -formatter friendly
        -exclude ./**/mock
        ./..."

  pre-commit:
    desc: "Run all pre-commit tasks"
    cmds:
      - task: format
      - task: lint
      - task: test

  deps:
    desc: "Install all dependencies"
    cmds:
      - GOBIN={{.GOBIN}} go install golang.org/x/tools/cmd/goimports@v0.19.0
      - GOBIN={{.GOBIN}} go install github.com/mgechev/revive@v1.3.7
      - GOBIN={{.GOBIN}} go install github.com/golang/mock/mockgen@v1.6.0
      - GOBIN={{.GOBIN}} go install github.com/google/yamlfmt/cmd/yamlfmt@v0.12.1
      - GOBIN={{.GOBIN}} go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@v2.5.0

## DOCKER

  docker-build:
    cmds:
      - docker build -t {{.DOCKER_IMAGE}}:{{.VERSION}} . 
        --build-arg VERSION={{.VERSION}}
        --no-cache

  docker-push:
    cmds:
      - docker push {{.DOCKER_IMAGE}}:{{.VERSION}}

  docker-release:
    cmds:
      - task: docker-build
      - task: docker-push

## INTERNAL COMMANDS

  go_files:
    desc: "Return all .go files and run .COMMAND on them"
    internal: true
    cmds:
     - find .
        -name "*.go"
        -not -path ./mock
        -exec {{.COMMAND}};
