name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v2

      - name: setup_go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: install_dependencies
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task deps
        shell: bash

      - name: run_linter
        run: task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v2

      - name: setup_go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: install_dependencies
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task deps
        shell: bash

      - name: run_tests
        run: task test

      - name: upload_coverage_reports_to_codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docker:
    if: github.ref == 'refs/heads/main'
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v2

      - name: setup_docker_buildx
        uses: docker/setup-buildx-action@v2

      - name: login_to_docker
        uses: docker/login-action@v2
        with:
          username: catalystgo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: build_and_push_docker_image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            catalystgo/protosync:latest
          build-args: |
            VERSION=latest
